### PR TITLE
fix travis-ci builds by removing old bazel versions and allow os x to fail

### PR DESCRIPTION
**Pull request by evie404**
we cannot assert whether our fork works if CI fails consistently. let's make CI pass first to have a decent baseline.

see #241

### CODE REVIEW

**Comment by promiseofcake** [comment]
As we are moving this in-house it might make sense to limit the Travis ~changesets~ runs because it seems like we are building 4 different ones now.

**Comment by evie404** [comment]
@promiseofcake yeah i'm experimenting with the travis setup a bit... it seems to be triggering on

- travis-ci.org
- travis-ci.com

and for:

- PR
- pushes

which meant 4 builds in total.

i turned on the "Auto Cancellation" but that doesn't seem to prevent duplicate builds between PR/pushes... maybe i'm understand the feature incorrectly.

i'll turn off the integration for `travis-ci.com` so that it doesn't interfere with our paid quotas.

**Comment by promiseofcake** [comment]
This seems good -- I think the red x is from a cancelled build correct?

**Comment by evie404** [comment]
red x is from the cancelled build yes

**Review by promiseofcake — APPROVED** [review]

**Pull request merged**
