### PR TITLE
Bazel 0.29.1 HEAD!!!!!!

### PR DESCRIPTION
**Pull request by evie404**
idk... I got this working with Bazel 0.29.1 which is basically HEAD omg

### CODE REVIEW

**Comment by promiseofcake** [comment]
How does that even work! The other flags we are using should have been removed at this point! But I love it.

**Comment by evie404** [comment]
@promiseofcake 

I think it's because they have a moratorium 

> With Bazel 0.27, we start a 3 month stability window. Bazel 0.28 and Bazel 0.29 will be backward compatible with Bazel 0.27.

- https://blog.bazel.build/2019/06/17/bazel-0.27.0.html

build fails on mac though due to python stuff... will look into it

**Comment by promiseofcake** [comment]
Ah ha! Thanks!

**Comment by evie404** [comment]
omg so this actually passed on:

- Bazel 0.29.1: https://travis-ci.org/vsco/rules_protobuf/builds/588763515
- Bazel 0.28.1: https://travis-ci.org/vsco/rules_protobuf/builds/588763574
- Bazel 0.27.2: https://travis-ci.org/vsco/rules_protobuf/builds/588763661

**Comment by promiseofcake** [comment]
:shipit:

**Review by promiseofcake — APPROVED** [review]

**Comment by melindalu** [comment]
whoa

**Comment by akakitani** [comment]
😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮 😮

**Pull request merged**
