### PR TITLE
update to rules_go 0.17.x

### PR DESCRIPTION
**Pull request by evie404**

### CODE REVIEW

**Comment by promiseofcake** [comment]
Do we need to do something to kick-off travis here? By config it seems like it should build on this PR to master.

**Comment by evie404** [comment]
travis happened but idk why it's not reporting status here :/ https://travis-ci.org/vsco/rules_protobuf/builds/571554290

**Comment by promiseofcake** [comment]
Ah I think it's because this is from a forked repo as opposed to branch of this repo as was done in #8

**Comment by evie404** [comment]
oh right...

**Comment by evie404** [comment]
tests passed! https://travis-ci.org/vsco/rules_protobuf/builds/571883197

**Review by promiseofcake — APPROVED** [review]

**Pull request merged**
